In [1]:
import pandas as pd

In [2]:
def my_sq(x):
    return x**2

In [3]:
# apply basic function 
df = pd.DataFrame({"a":[10,20,30],"b":[20,30,40]})
print(df['a']**2)

0    100
1    400
2    900
Name: a, dtype: int64

In [4]:
df

    a   b
0  10  20
1  20  30
2  30  40

In [5]:
# apply over series
df['a'].apply(my_sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [6]:
# apply over dataframe
# we pass axis=0 or axis='index' to apply method column wise axis=1 or axis ='column' to apply method row wise
def print_me(x):
    return(x)
# column wise operation, axis = 0
df.apply(print_me, axis=0)
# column wise operation, axis = 'index'
df.apply(print_me, axis='index')

    a   b
0  10  20
1  20  30
2  30  40

In [7]:
# row wise operation, axis = 1
df.apply(print_me, axis=1)
# row wise operation, axis = 'columns'
df.apply(print_me, axis='columns')

    a   b
0  10  20
1  20  30
2  30  40

In [8]:
def avg(col):
    x = col[0]
    y = col[1]
    z = col[2] 
    return (x+y+z)/3
df.apply(avg,axis=0)

a    20.0
b    30.0
dtype: float64

In [9]:
def avg(col):
    x = col[0]
    y = col[1]
    return (x+y)/2
df.apply(avg,axis=1)

C:\Users\DELL\AppData\Local\Temp\ipykernel_6272\3957532596.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  x = col[0]
C:\Users\DELL\AppData\Local\Temp\ipykernel_6272\3957532596.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  y = col[1]

0    15.0
1    25.0
2    35.0
dtype: float64

# vectorize with numpy

In [10]:
import numpy as np

In [26]:
def avg2(x,y):
    if x == 20:
        return np.nan
    else:
        return (x+y)/2

In [30]:
# after vectorizing function can accepct vector as argument
average = np.vectorize(avg2)

In [28]:
print(average(df['a'],df['b']))

[15. nan 35.]

# lambda function

In [31]:
def sqa(x):
    return x**2

In [33]:
df['a_sq'] = df['a'].apply(sqa)

In [34]:
df

    a   b  a_sq
0  10  20   100
1  20  30   400
2  30  40   900

In [38]:
df['b_sq'] =df['b'].apply(lambda x:x**2)

In [39]:
df

    a   b  a_sq  b_sq
0  10  20   100   400
1  20  30   400   900
2  30  40   900  1600