In [2]:
import pandas as pd

# combine dataframe

In [3]:
import pandas as pd

df1 = pd.read_csv("df1.csv")
df2 = pd.read_csv("df2.csv")
df3 = pd.read_csv("df3.csv")

In [4]:
df1

   A  B  C  D
0  0  0  0  0
1  1  1  1  1
2  2  2  2  2
3  3  3  3  3

In [5]:
row_concat = pd.concat([df1,df2,df3])

In [6]:
# adds rows to dataframe if the data tyoe of the object is dataframe
row_concat

    A   B   C   D
0   0   0   0   0
1   1   1   1   1
2   2   2   2   2
3   3   3   3   3
0   4   4   4   4
1   5   5   5   5
2   6   6   6   6
3   7   7   7   7
0   8   8   8   8
1   9   9   9   9
2  10  10  10  10
3  11  11  11  11

In [7]:
new_series = pd.Series(['n1','n2','n3','n4'])

In [8]:
# add to new column 0
pd.concat([row_concat,new_series])

      A     B     C     D    0
0   0.0   0.0   0.0   0.0  NaN
1   1.0   1.0   1.0   1.0  NaN
2   2.0   2.0   2.0   2.0  NaN
3   3.0   3.0   3.0   3.0  NaN
0   4.0   4.0   4.0   4.0  NaN
1   5.0   5.0   5.0   5.0  NaN
2   6.0   6.0   6.0   6.0  NaN
3   7.0   7.0   7.0   7.0  NaN
0   8.0   8.0   8.0   8.0  NaN
1   9.0   9.0   9.0   9.0  NaN
2  10.0  10.0  10.0  10.0  NaN
3  11.0  11.0  11.0  11.0  NaN
0   NaN   NaN   NaN   NaN   n1
1   NaN   NaN   NaN   NaN   n2
2   NaN   NaN   NaN   NaN   n3
3   NaN   NaN   NaN   NaN   n4

In [9]:
new_df = pd.DataFrame(
    data = [['n1','n2','n3','n4']],
    columns = ['A','B','C','D']
)

In [10]:
# dataframe is added to row
pd.concat([row_concat,new_series])

      A     B     C     D    0
0   0.0   0.0   0.0   0.0  NaN
1   1.0   1.0   1.0   1.0  NaN
2   2.0   2.0   2.0   2.0  NaN
3   3.0   3.0   3.0   3.0  NaN
0   4.0   4.0   4.0   4.0  NaN
1   5.0   5.0   5.0   5.0  NaN
2   6.0   6.0   6.0   6.0  NaN
3   7.0   7.0   7.0   7.0  NaN
0   8.0   8.0   8.0   8.0  NaN
1   9.0   9.0   9.0   9.0  NaN
2  10.0  10.0  10.0  10.0  NaN
3  11.0  11.0  11.0  11.0  NaN
0   NaN   NaN   NaN   NaN   n1
1   NaN   NaN   NaN   NaN   n2
2   NaN   NaN   NaN   NaN   n3
3   NaN   NaN   NaN   NaN   n4

# add columns

In [11]:
col_concat = pd.concat([df1,df2,df3],axis = 'columns')

In [12]:
# added column wise
col_concat

   A  B  C  D  A  B  C  D   A   B   C   D
0  0  0  0  0  4  4  4  4   8   8   8   8
1  1  1  1  1  5  5  5  5   9   9   9   9
2  2  2  2  2  6  6  6  6  10  10  10  10
3  3  3  3  3  7  7  7  7  11  11  11  11

In [13]:
col_concat['newlist'] = ['n1','n2','n3','n4']

In [14]:
col_concat

   A  B  C  D  A  B  C  D   A   B   C   D newlist
0  0  0  0  0  4  4  4  4   8   8   8   8      n1
1  1  1  1  1  5  5  5  5   9   9   9   9      n2
2  2  2  2  2  6  6  6  6  10  10  10  10      n3
3  3  3  3  3  7  7  7  7  11  11  11  11      n4

# concatinate different row with column

In [15]:

df1.columns = ['A','B','C','D']
df2.columns = ['E','F','G','H']
df3.columns = ['A','C','F','H']

In [16]:
row_concat = pd.concat([df1,df2,df3])

In [17]:
# valunes under the same column name comws in same column
row_concat

      A    B     C    D    E     F    G     H
0   0.0  0.0   0.0  0.0  NaN   NaN  NaN   NaN
1   1.0  1.0   1.0  1.0  NaN   NaN  NaN   NaN
2   2.0  2.0   2.0  2.0  NaN   NaN  NaN   NaN
3   3.0  3.0   3.0  3.0  NaN   NaN  NaN   NaN
0   NaN  NaN   NaN  NaN  4.0   4.0  4.0   4.0
1   NaN  NaN   NaN  NaN  5.0   5.0  5.0   5.0
2   NaN  NaN   NaN  NaN  6.0   6.0  6.0   6.0
3   NaN  NaN   NaN  NaN  7.0   7.0  7.0   7.0
0   8.0  NaN   8.0  NaN  NaN   8.0  NaN   8.0
1   9.0  NaN   9.0  NaN  NaN   9.0  NaN   9.0
2  10.0  NaN  10.0  NaN  NaN  10.0  NaN  10.0
3  11.0  NaN  11.0  NaN  NaN  11.0  NaN  11.0

# concat columns with different rows

In [27]:
df1.index = [0,1,2,3]
df2.index = [4,5,6,7]
df3.index = [0,2,5,7]

In [28]:
col_concat = pd.concat([df1,df2,df3],axis = 'columns')

In [29]:
col_concat

     A    B    C    D    E    F    G    H     A     C     F     H
0  0.0  0.0  0.0  0.0  NaN  NaN  NaN  NaN   8.0   8.0   8.0   8.0
1  1.0  1.0  1.0  1.0  NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN
2  2.0  2.0  2.0  2.0  NaN  NaN  NaN  NaN   9.0   9.0   9.0   9.0
3  3.0  3.0  3.0  3.0  NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN
4  NaN  NaN  NaN  NaN  4.0  4.0  4.0  4.0   NaN   NaN   NaN   NaN
5  NaN  NaN  NaN  NaN  5.0  5.0  5.0  5.0  10.0  10.0  10.0  10.0
6  NaN  NaN  NaN  NaN  6.0  6.0  6.0  6.0   NaN   NaN   NaN   NaN
7  NaN  NaN  NaN  NaN  7.0  7.0  7.0  7.0  11.0  11.0  11.0  11.0