In [2]:
import pandas as pd

# Aggregate
### aggregation is process of taking multiple values and return a single value e.g. arithmetic mean

## basic one-variable group aggregate

In [3]:
# default argument required for .tsv files
df = pd.read_csv('gapminder.tsv',sep='\t')

In [4]:
df

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [5]:
life_exp =  df.groupby('year')['lifeExp'].mean()

In [6]:
# life expentancy for every year
life_exp

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [7]:
# subset data for 1952
y1952 = df.loc[df.year == 1952,:]
y1952

                 country continent  year  lifeExp       pop    gdpPercap
0            Afghanistan      Asia  1952   28.801   8425333   779.445314
12               Albania    Europe  1952   55.230   1282697  1601.056136
24               Algeria    Africa  1952   43.077   9279525  2449.008185
36                Angola    Africa  1952   30.015   4232095  3520.610273
48             Argentina  Americas  1952   62.485  17876956  5911.315053
...                  ...       ...   ...      ...       ...          ...
1644             Vietnam      Asia  1952   40.412  26246839   605.066492
1656  West Bank and Gaza      Asia  1952   43.160   1030585  1515.592329
1668         Yemen, Rep.      Asia  1952   32.548   4963829   781.717576
1680              Zambia    Africa  1952   42.038   2672000  1147.388831
1692            Zimbabwe    Africa  1952   48.451   3080907   406.884115

[142 rows x 6 columns]

In [8]:
# life expentancy for 1952 year
y1952_mean = y1952['lifeExp'].mean()
y1952_mean

np.float64(49.057619718309866)

# Built in aggregative methods

### Table 8.1: Methods and Functions That Can Be Used With `.groupby()`

| Pandas Method       | NumPy / SciPy Function   | Description                                      |
| ------------------- | ------------------------ | ------------------------------------------------ |
| `.count()`          | `np.count_nonzero()`     | Frequency count not including NaN values         |
| `.size()`           | —                        | Frequency count including NaN values             |
| `.mean()`           | `np.mean()`              | Mean of the values                               |
| `.std()`            | `np.std()`               | Sample standard deviation                        |
| `.min()`            | `np.min()`               | Minimum values                                   |
| `.quantile(q=0.25)` | `np.percentile(q=0.25)`  | 25th percentile of the values                    |
| `.quantile(q=0.50)` | `np.percentile(q=0.50)`  | 50th percentile of the values                    |
| `.quantile(q=0.75)` | `np.percentile(q=0.75)`  | 75th percentile of the values                    |
| `.max()`            | `np.max()`               | Maximum value                                    |
| `.sum()`            | `np.sum()`               | Sum of the values                                |
| `.var()`            | `np.var()`               | Unbiased variance                                |
| `.sem()`            | `scipy.stats.sem()`      | Unbiased standard error of the mean              |
| `.describe()`       | `scipy.stats.describe()` | Count, mean, std, min, 25%, 50%, 75%, max        |
| `.first()`          | —                        | Returns the first row                            |
| `.last()`           | —                        | Returns the last row                             |
| `.nth()`            | —                        | Returns the nth row (Python index starts from 0) |

In [9]:
cont = df.groupby('continent')['lifeExp'].describe()
cont

,count,mean,std,min,25%,50%,75%,max
continent,,,,,,,,
Africa,624.0,48.865330,9.150210,23.599,42.37250,47.7920,54.41150,76.442
Americas,300.0,64.658737,9.345088,37.579,58.41000,67.0480,71.69950,80.653
Asia,396.0,60.064903,11.864532,28.801,51.42625,61.7915,69.50525,82.603
Europe,360.0,71.903686,5.433178,43.585,69.57000,72.2410,75.45050,81.757
Oceania,24.0,74.326208,3.795611,69.120,71.20500,73.6650,77.55250,81.235

# aggrigation function
## custom function

In [10]:
def my_mean(val):
    n=len(val)
    return val.sum()/n

In [11]:
df.groupby('year')['lifeExp'].agg(my_mean)

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [12]:
diff_val = df['lifeExp'].mean()
diff_val

np.float64(59.474439366197174)

In [13]:
def diffmean(val,diff):
    n = len(val)
    Sum = 0
    for value in val:
        Sum += value
    mean = Sum/n
    return mean - diff

In [14]:
mean_diff = df.groupby('year')['lifeExp'].agg(diffmean,diff=diff_val)

In [15]:
mean_diff

year
1952   -10.416820
1957    -7.967038
1962    -5.865190
1967    -3.796150
1972    -1.827053
1977     0.095718
1982     2.058758
1987     3.738173
1992     4.685899
1997     5.540237
2002     6.220483
2007     7.532983
Name: lifeExp, dtype: float64

In [16]:
df

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

# use dictonary in .agg()/aggregate()
## on dataframe

In [17]:
# calculating mean, median for lifeexp,pop,gdppercap
gdpdict = df.groupby('year').agg({'lifeExp':'mean','pop':'median','gdpPercap':'median'})

In [18]:
gdpdict

        lifeExp         pop    gdpPercap
year
1952  49.057620   3943953.0  1968.528344
1957  51.507401   4282942.0  2173.220291
1962  53.609249   4686039.5  2335.439533
1967  55.678290   5170175.5  2678.334740
1972  57.647386   5877996.5  3339.129407
1977  59.570157   6404036.5  3798.609244
1982  61.533197   7007320.0  4216.228428
1987  63.212613   7774861.5  4280.300366
1992  64.160338   8688686.5  4386.085502
1997  65.014676   9735063.5  4781.825478
2002  65.694923  10372918.5  5319.804524
2007  67.007423  10517531.0  6124.371108

## on series

In [19]:
import numpy as np

In [20]:
# average, mean, standerd deviation of the lifeExp series
gdp = df.groupby('year')['lifeExp'].agg([np.count_nonzero,np.mean,np.std]).rename({'count_nonzero':'count','mean':'avg','std':'std_dev'})
gdp

C:\Users\DELL\AppData\Local\Temp\ipykernel_21364\3372287845.py:2: FutureWarning: The provided callable <function mean at 0x000001C2AAE5FE20> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  gdp = df.groupby('year')['lifeExp'].agg([np.count_nonzero,np.mean,np.std]).rename({'count_nonzero':'count','mean':'avg','std':'std_dev'})
C:\Users\DELL\AppData\Local\Temp\ipykernel_21364\3372287845.py:2: FutureWarning: The provided callable <function std at 0x000001C2AAE5FF60> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  gdp = df.groupby('year')['lifeExp'].agg([np.count_nonzero,np.mean,np.std]).rename({'count_nonzero':'count','mean':'avg','std':'std_dev'})

      count_nonzero       mean        std
year
1952            142  49.057620  12.225956
1957            142  51.507401  12.231286
1962            142  53.609249  12.097245
1967            142  55.678290  11.718858
1972            142  57.647386  11.381953
1977            142  59.570157  11.227229
1982            142  61.533197  10.770618
1987            142  63.212613  10.556285
1992            142  64.160338  11.227380
1997            142  65.014676  11.559439
2002            142  65.694923  12.279823
2007            142  67.007423  12.073021

# Transform

## Z score Example
### formula = x-µ/σ x= data
### point in dataframe 
### µ= average of dataframe= sum of data points/no. of data points
### σ= standerd SD = √[ Σ(x − µ)² / n ]

In [21]:
def my_zval(x):
    return (x-x.mean())/x.std()

In [22]:
# calculating grouped data zscors
z_value = df.groupby('year')['lifeExp'].transform(my_zval)

In [23]:
z_value

0      -1.656854
1      -1.731249
2      -1.786543
3      -1.848157
4      -1.894173
          ...
1699   -0.081621
1700   -0.336974
1701   -1.574962
1702   -2.093346
1703   -1.948180
Name: lifeExp, Length: 1704, dtype: float64

#### scipy owns zscore() function

In [24]:
from scipy.stats import zscore

In [25]:
df.groupby('year')['lifeExp'].transform(zscore)

0      -1.662719
1      -1.737377
2      -1.792867
3      -1.854699
4      -1.900878
          ...
1699   -0.081910
1700   -0.338167
1701   -1.580537
1702   -2.100756
1703   -1.955077
Name: lifeExp, Length: 1704, dtype: float64

In [26]:
# calculating non grouped data zscors
z_score = zscore(df['lifeExp'])

In [ ]:
import seaborn as sns

In [ ]:
# set seed so the results are deterministic
np.random.seed(42)

In [ ]:
# saple 10 rows form tips
tips_10 = sns.load_dataset('tips').sample(10)

In [ ]:
tips_10

In [ ]:
tips_10.loc[np.random.permutation(tips_10.index)[:4],'total_bill'] = np.nan

In [ ]:
tips_10

In [ ]:
def fill_na(x):
    avg = x.mean()
    return x.fillna(avg)

In [ ]:
total_bill_group = (tips_10.groupby('sex').total_bill.transform(fill_na))

In [ ]:
tips_10['fill_avg'] = total_bill_group

In [ ]:
tips_10

# Filter

In [ ]:
# load the tips dataset
tips = sns.load_dataset('tips')
tips

In [ ]:
tips.shape

In [ ]:
tips['size'].value_counts()

In [ ]:
# filter the data such that each group has more then 30 observations
tip_filter = tips.groupby('size').filter(lambda x:x['size'].count()>=30)
tip_filter

In [ ]:
tip_filter.value_counts('size')

In [ ]:
tips_10